# 101 NumPy Exercises

## 1. Import numpy as np and see the version

In [4]:
import numpy as np
print(np.__version__)

1.20.2


## 2. How to create a 1D array?

In [4]:
numbers = np.arange(10)
numbers

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## 3. How to create a boolean array?

In [5]:
np.ones((3, 3), dtype=bool)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

## 4. How to extract items that satisfy a given condition from 1D array?

In [6]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
arr[arr%2 == 1]

array([1, 3, 5, 7, 9])

## 5. How to replace items that satisfy a condition with another value in numpy array?

In [7]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
arr[arr%2 == 1] = -1
arr

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

## 6. How to replace items that satisfy a condition without affecting the original array?

In [8]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
out = np.where(arr % 2 == 1, -1, arr)
print("Out:",out)
print("Arr:",arr)

Out: [ 0 -1  2 -1  4 -1  6 -1  8 -1]
Arr: [0 1 2 3 4 5 6 7 8 9]


## 7. How to reshape an array?

In [9]:
arr = np.arange(10)
# https://numpy.org/doc/stable/reference/generated/numpy.reshape.html
reshapedArray = arr.reshape(2,-1) # -1 makes it shape automatically
reshapedArray

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

## 8. How to stack two arrays vertically?

In [10]:
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
# https://numpy.org/doc/stable/reference/generated/numpy.vstack.html#numpy.vstack
np.vstack([a,b])

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

## 9. How to stack two arrays horizontally?

In [11]:
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
# https://numpy.org/doc/stable/reference/generated/numpy.hstack.html
np.hstack([a,b])

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

## 10. How to generate custom sequences in numpy without hardcoding?

In [32]:
a = np.array([1,2,3])
# https://numpy.org/doc/stable/reference/generated/numpy.repeat.html
# https://numpy.org/doc/stable/reference/generated/numpy.tile.html
np.hstack([np.repeat(a, 3), np.tile(a, 3)])

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

## 11. How to get the common items between two python numpy arrays?

In [36]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
# https://numpy.org/doc/stable/reference/generated/numpy.intersect1d.html
np.intersect1d(a, b)

array([2, 4])

## 12. How to remove from one array those items that exist in another?

In [40]:
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])
# https://numpy.org/doc/stable/reference/generated/numpy.setdiff1d.html
np.setdiff1d(a,b,False)

array([1, 2, 3, 4])

## 13. How to get the positions where elements of two arrays match?

In [51]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
# https://stackoverflow.com/questions/47066197/check-two-arrays-for-matching-elements-given-the-same-index-and-return-number-of
np.where(a == b)

(array([1, 3, 5, 7]),)

## 14. How to extract all numbers between a given range from a numpy array?

In [60]:
a = np.array([2, 6, 1, 9, 10, 3, 27])
indices = np.where((a > 5) & (a < 11))
a[indices]

array([ 6,  9, 10])

## 15. How to make a python function that handles scalars to work on numpy arrays?

In [22]:
def maxx(x, y):
    """Get the maximum of two items"""
    if x >= y:
        return x
    else:
        return y

pair_max = np.vectorize(maxx, otypes=[int])

a = np.array([5, 7, 9, 8, 6, 4, 5])
b = np.array([6, 3, 4, 8, 9, 7, 1])
np.set_printoptions(threshold=sys.maxsize)
pair_max(a, b)

array([6, 7, 9, 8, 9, 7, 5])

## 16. How to swap two columns in a 2d numpy array?

In [119]:
arr = np.arange(9).reshape(3,3)
arr
arr[:,[1, 0, 2]]

array([[1, 0, 2],
       [4, 3, 5],
       [7, 6, 8]])

## 17. How to swap two rows in a 2d numpy array?

In [120]:
arr = np.arange(9).reshape(3,3)
arr
arr[[1, 0, 2], :]

array([[3, 4, 5],
       [0, 1, 2],
       [6, 7, 8]])

## 18. How to reverse the rows of a 2D array?

In [122]:
arr = np.arange(9).reshape(3,3)
# https://numpy.org/doc/stable/reference/generated/numpy.flip.html
np.flip(arr, 0)

array([[6, 7, 8],
       [3, 4, 5],
       [0, 1, 2]])

## 19. How to reverse the columns of a 2D array?

In [126]:
arr = np.arange(9).reshape(3,3)
# https://numpy.org/doc/stable/reference/generated/numpy.flip.html
np.flip(arr, 1)

array([[2, 1, 0],
       [5, 4, 3],
       [8, 7, 6]])

## 20. How to create a 2D array containing random floats between 5 and 10?

In [127]:
randomArray = np.random.uniform(5,10, size=(5,3))
# https://numpy.org/doc/stable/reference/random/generated/numpy.random.uniform.html
print(randomArray)

[[7.87546665 9.45660977 6.04601061]
 [5.9266411  5.54188445 6.09848746]
 [9.89311892 9.05841575 5.85970506]
 [9.08112374 6.37036874 7.15852092]
 [9.7001491  9.08824689 6.68055975]]


## 21. How to print only 3 decimal places in python numpy array?

In [7]:
rand_arr = np.random.random((5,3))
np.set_printoptions(precision=3)
rand_arr

array([[0.431, 0.028, 0.863],
       [0.983, 0.648, 0.576],
       [0.628, 0.673, 0.442],
       [0.666, 0.907, 0.981],
       [0.72 , 0.872, 0.468]])

## 22. How to pretty print a numpy array by suppressing the scientific notation (like 1e10)?

In [18]:
np.random.seed(100)
rand_arr = np.random.random([3,3])/1e3
np.set_printoptions(suppress=True, precision=6)
rand_arr

array([[0.000543, 0.000278, 0.000425],
       [0.000845, 0.000005, 0.000122],
       [0.000671, 0.000826, 0.000137]])

## 23. How to limit the number of items printed in output of numpy array?

In [24]:
a = np.arange(15)
np.set_printoptions(threshold=5)
a

array([ 0,  1,  2, ..., 12, 13, 14])

## 24. How to print the full numpy array without truncating

In [25]:
np.set_printoptions(threshold=6)
a = np.arange(15)
np.set_printoptions(threshold=sys.maxsize)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

## 25. How to import a dataset with numbers and texts keeping the text intact in python numpy?

In [32]:
url = 'https://raw.githubusercontent.com/edlich/eternalrepo/master/DS-WAHLFACH/countries.csv'
countries = np.genfromtxt(url, delimiter=',', dtype='object')
names = ('Name', 'People', 'Area', 'BIP', 'Currency')
countries[:sys.maxsize]

array([[b'Name', b'People', b'Area', b'BIP', b'Currency'],
       [b'Germany', b'82521653', b'357385', b'3466', b'EUR'],
       [b'Japan', b'126045000', b'377835', b'4938', b'YEN'],
       [b'Canada', b'36503097', b'9984670', b'1529', b'CAD'],
       [b'Italy', b'60501718', b'301338', b'1850', b'EUR'],
       [b'Brazilia', b'208360000', b'8515770', b'1798', b'REAL']],
      dtype=object)